name: publish

on:
  push:
    branches:
      - master
    paths:
      - package.json

env:
  CI: true

permissions:
  contents: write
  packages: write

jobs:
  publish:
    uses: haraka/.github/.github/workflows/publish.yml@master
    secrets: inherit
